// ap_sd_num(key, fallback) -- read one number out of slot_data.
//
// Only valid while the ap_slot_connected event is being dispatched: proxy 0 is
// that event's argument, which for ap_slot_connected IS the slot_data object.
//
// The fallback matters. A slot generated by an older apworld will not carry
// every key this build knows about, and reading a missing key would quietly
// configure the game to zero -- zero shop tiers, zero prices. Fall back to
// whatever ap_tables.gml baked in instead.

if (external_call(global.ext_ap_json_exists, 0, argument0))
{
    return external_call(global.ext_ap_json_number_at, 0, argument0);
}
return argument1;
